version = 1

[[annotations]]
path = [
  ".editorconfig",
  ".gitignore",
  "flake.lock",
  "flake.nix",
  "forest.toml",
  "justfile",
  "typos.toml",
  "README.md",
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["trees/*"]
SPDX-FileCopyrightText = "2024 polykernel"
SPDX-License-Identifier = ["CC-BY-NC-SA-4.0", "MIT"]

[[annotations]]
path = ["files/CNAME", "files/robots.txt"]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"
