# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# SPDX-FileCopyrightText: NONE
# SPDX-License-Identifier: CC0-1.0

name: Build and deploy site

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.forgejo/**'
      - 'trees/*'
      - 'assets/*'
      - 'files/*'
      - 'flake.lock'
      - 'forest.toml'
      - 'website.nix'

jobs:
  build_and_deploy:
    name: Build and deploy
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout source
        uses: https://data.forgejo.org/actions/checkout@v6

      - name: Install Nix
        uses: https://github.com/NixOS/nix-installer-action@main
        with:
          init: no
          extra-conf: |
            extra-substituters = https://forester.cachix.org
            extra-trusted-public-keys = forester.cachix.org-1:pErGVVci7kZWxxcbQ/To8Lvqp6nVTeyPf0efJxbrQDM=

      - name: Build site
        shell: sh
        run: |
          nix build .#website
          cp --recursive --dereference --no-preserve=mode,ownership result dist

      - name: Deploy to Cloudflare Pages
        uses: https://github.com/cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=perennial-curiosity

      - name: Upload pages artifact
        uses: https://data.forgejo.org/forgejo/upload-artifact@v4
        with:
          name: pages
          path: dist
          retention-days: 7
          if-no-files-found: error
