# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# SPDX-FileCopyrightText: NONE
# SPDX-License-Identifier: CC0-1.0

name: Build and deploy site

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/**'
      - 'trees/*'
      - 'assets/*'
      - 'flake.nix'
      - 'flake.lock'
      - 'forest.toml'
      - 'website.nix'

jobs:
  build_and_deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup netrc
        shell: sh
        run: |
          mkdir ${{ runner.temp }}/nix
          echo "machine attic.polykernel.cc password ${{ secrets.ATTIC_CACHE_JWT }}" > ${{ runner.temp }}/nix/netrc

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: |
            trusted-public-keys = perennial-curiosity:3NPFo27amY6UkSwdflZjpCiEE13ulY4gI5tB8MFlbiU= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://attic.polykernel.cc/perennial-curiosity https://cache.nixos.org/
            netrc-file = ${{ runner.temp }}/nix/netrc

      - name: Build site
        shell: sh
        run: |
          nix build --accept-flake-config
          cp --recursive --dereference --no-preserve=mode,ownership result dist

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=perennial-curiosity

      - name: Upload pages artifact
        uses: actions/upload-artifact@v4
        with:
          name: pages
          path: dist
          retention-days: 7
          if-no-files-found: error
