# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# SPDX-FileCopyrightText: NONE
# SPDX-License-Identifier: CC0-1.0

name: Build and deploy site

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    name: Build and deploy
    env:
      cacheName: perennial-curiosity
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Path filter
        id: path-filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            deploy:
              - '.github/**'
              - 'trees/*'
              - 'assets/*'
              - 'flake.nix'
              - 'flake.lock'
              - 'forest.toml'
              - 'website.nix'

      - name: Install Nix
        uses: cachix/install-nix-action@v30

      - name: Setup cachix
        uses: cachix/cachix-action@v15
        with:
          name: ${{ env.cacheName }}
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build site
        shell: sh
        run: |
          nix build --accept-flake-config
          cp --recursive --dereference --no-preserve=mode,ownership result dist

      - name: Deploy to Cloudflare Pages
        if: steps.path-filter.outputs.deploy == 'true'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=perennial-curiosity

      - name: Upload pages artifact
        uses: actions/upload-artifact@v4
        with:
          name: pages
          path: dist
          retention-days: 7
          if-no-files-found: error
